version: '3.8'

services:
  capptain-backend:
    container_name: capptain-backend
    build: .
    #command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - '8000:8000'
    volumes:
      - .:/usr/src/capptain-backend
    depends_on:
      - capptain-database

  capptain-database:
    container_name: capptain-database
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_DB=capptain
      - POSTGRES_USER=localhost
      - POSTGRES_PASSWORD=localhost
    ports:
      - '5432:5432'
