# Generated by Django 5.0.4 on 2024-04-23 12:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("capptain", "0003_teamplayers"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TeamPlayers",
            new_name="TeamPlayer",
        ),
        migrations.AlterModelOptions(
            name="match",
            options={"verbose_name_plural": "Matches"},
        ),
    ]
