# Generated by Django 5.0.4 on 2024-04-26 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capptain", "0006_alter_match_team"),
    ]

    operations = [
        migrations.AlterField(
            model_name="match",
            name="joining_players",
            field=models.ManyToManyField(
                blank=True, related_name="joining_players", to="capptain.teamplayer"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="no_answer_players",
            field=models.ManyToManyField(
                blank=True, related_name="no_answer_players", to="capptain.teamplayer"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="not_joining_players",
            field=models.ManyToManyField(
                blank=True, related_name="not_joining_players", to="capptain.teamplayer"
            ),
        ),
        migrations.AlterField(
            model_name="match",
            name="spectating_players",
            field=models.ManyToManyField(
                blank=True, related_name="spectating_players", to="capptain.teamplayer"
            ),
        ),
    ]
